version: "3.8"
services:
  python_api:
    build: ./python_api
    container_name: python_api
    ports:
      - "8000:8000"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PYTHON_API_URL=http://python_api:8000/summarize
    depends_on:
      - python_api

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
