version: "3.8"

services:
  fastapi:
    build: ./fastapi_service
    container_name: fastapi_service
    ports:
      - "8001:8001"

  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "5000:5000"
    environment:
      FASTAPI_URL: http://fastapi:8001
    depends_on:
      - fastapi

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
